### ISSUE TITLE
BMS - Full.key - last line deletion

### ISSUE THREAD

**Issue by etcher-be** [chihirobelmo/FalconBMS-Alternative-Launcher#10]
Hi !

First of all, thanks a bunch for this app, it's a true lifesaver :1st_place_medal: 

I think I found an issue with it, but I'm a total Falcon noob so it might be just me.

It seems that every time the Alternative Launcher exits, it removes the last line from the "default" `BMS - Full.key`.

I'm using Git to backup my config, and I see this behavior consistently. 

I've attached a diff showing exactly what I mean.

Please let me know if you need more info !

![diff](https://user-images.githubusercontent.com/21277151/57178059-71202980-6e6b-11e9-9208-f903a1021a43.png)

**Comment by chihirobelmo** [comment]
Thank you! I found a bad code and it seems happens to everyone. I will fix/test and release a fixed version.

**Comment by etcher-be** [comment]
Awesome ! Glad to help, and a bunch of thanks again for making this :+1:

**Comment by chihirobelmo** [comment]
Fixed in v1.31.
