### ISSUE TITLE
POV keylines are only outputting the bindings for the first POV in 'BMS - Auto.key'

### ISSUE THREAD

**Issue by Althar93** [chihirobelmo/FalconBMS-Alternative-Launcher#102]
I was trying to setup my joystick (VKB Gunfight) so that both POVs were active & bound & found that my 'BMS - Auto.key' would only contains keylines the first POV.

Upon inspection of the source code, I discovered that **OverrideSettingsFor434U1.cs** **WriteKeyLines** will only output keyline information for POV 0 when using separate roll & throttle axis devices :

`if (rollAxis.GetDeviceNumber() == i)
                    sw.Write(deviceControl.joyAssign[i].GetKeyLinePOV(0));`

By changing the 'GetKeyLinePOV(0)' to 'GetKeyLinePOV()', the BMS - Auto.key will correctly contains all bindings for all povs on that device. 

`if (rollAxis.GetDeviceNumber() == i)
                    sw.Write(deviceControl.joyAssign[i].GetKeyLinePOV());`

This works for me, but perhaps someone can sanity check & confirm whether this fix is legitimate?

**Comment by Althar93** [comment]
This is what I came up with : https://github.com/Althar93/FalconBMS-Alternative-Launcher/commit/6d7c1e979eca34a3ac36f2e0fc285761a9aab9b4

**Comment by arithex** [comment]
I basically did same, or similar thing in pull/101 .. but I don't have a device with two 8-way pov hats, to test it.  

I was setting out to fix the nearby/related bug (issues/93), re the shifted-states are horked for pov hats.

I'd recommend testing any fix with multiple devices plugged in (eg. if you have a spare PC game controller or something handy).

(I need to do more testing on pull/101 too.)

**Comment by Althar93** [comment]
Interesting. In my case/testing, I had a VKB Gunfighter MCG Pro (with two POV hats) and a Mongoos CM3.

Happy to test with more devices/POV hats and report back.

I can take a look into this later today and post the resulting BMS - Auto.key and how BMS reacts.

**Comment by arithex** [comment]
Closing this as fixed, for BMS 4.37 U3 (AL bits available in latest develop-branch build).

BUT if you are able to test on a device with 2 hats, let me know how that works.   (Reopen this issue or cut a new one.)
