### ISSUE TITLE
Keymapping gets stuck with Pinky Switch (Shift)

### ISSUE THREAD

**Issue by Oceans31st** [chihirobelmo/FalconBMS-Alternative-Launcher#119]
I installed 4.37.3 with the Full Installer. I am using a Saitek X-65F + Rudders and no profile is loaded into the hotas.

The axes were all automatically set correctly and when setting the keymappings, TMS, DMS, CMS and Trim were also set correctly.
Something goes wrong when setting the Pinky Switch (Shift). I then get a window with the message: 
_"An unknown error occurred, check error log for details:"_
The error log shows abracadabra, see the attachment.
Then the other buttons (TMS, etc.) in the mapping page no longer work either.
What happens and what can I do?

[20231105_Oceans31st_Launcher_Log.txt](https://github.com/chihirobelmo/FalconBMS-Alternative-Launcher/files/13263783/20231105_Oceans31st_Launcher_Log.txt)

**Comment by arithex** [comment]
This looks like known bug fixed in PR #118.  Try the latest prerelease build, v2.4.1.4.
https://github.com/chihirobelmo/FalconBMS-Alternative-Launcher/releases/tag/v2.4.1.4

**Comment by Oceans31st** [comment]
So far so good. I used v2.4.1.4 and now I have been able to assign my buttons to the different functions.
