### ISSUE TITLE
KeyMapping "button release" doesn't work correctly

### ISSUE THREAD

**Issue by stouset** [chihirobelmo/FalconBMS-Alternative-Launcher#12]
From what I can tell, the line emitted into the `.key` file seems to be incompatible with BMS 4.34. For instance, when mapping my Warthog to call `SimIdleDetentForward` when it's moved forward out of the detents, it emits the following line:

```
SimThrottleIdleDetentForward 124 -1 -2 0x42 0x0 0
```

When in-sim, this doesn't actually work. The correct line (as best I can tell) would be

```
SimThrottleIdleDetentForward 124 -2 -2 0x42 0x0 0
                                 ^^
```

which does work.

FWIW I'm new to BMS and haven't been able to find documentation on the key file format, but experimenting with a few other editors led me to this, and it works. If I've misunderstood/misconfigured something, please let me know!

**Comment by chihirobelmo** [comment]
You can turn this line to -2 by push "INVOKE BOTH" button at KeyMapping page and change it to "INVOKE KEYDN" than assign DX buttons. 
You can find official documentation about the key file as BMS TECHNICAL MANUAL in the \Docs folder. 
I also don't have an idea of how these INVOKE line works, the official doc does not describe this that much, but yeah this needs to be -2 which means "invoke key down" when we want to call some callbacks by releasing a DX button.

I think I need a description of this at KeyMapping page. Thank you.

**Comment by stouset** [comment]
Gotcha, thanks!
