### ISSUE TITLE
The launcher shuts down after each keyassign action

### ISSUE THREAD

**Issue by metaphys** [chihirobelmo/FalconBMS-Alternative-Launcher#125]
hi,
when using the keyassign menu, as soon as the subwindows doing the assignment is opened, closing it either with the cross or the save button will cause the launcher to shutoff entirely. (if save is pressed the assignment is done correctly before closing)
This is a major hassle if one wants to reassign multiple keys/buttons

**Comment by arithex** [comment]
Any crash log?  please open `%LocalAppData%\Benchmark_Sims\Launcher_Log.txt` and share the contents, here or via https://pastebin.com/

**Comment by metaphys** [comment]
Sorry, to test it further I reinstalled the whole thing from scratch. Now I’m stuck with  #126

**Comment by metaphys** [comment]
after managing to turn around #126 and reinstalling from zero, it seems this is not happening anymore...
