### ISSUE TITLE
DeviceSorting problem

### ISSUE THREAD

**Issue by vakosel** [chihirobelmo/FalconBMS-Alternative-Launcher#13]
Hi there and wd for you work.
Actually my problem is not actually a problem of your program which works as expected with device sorting  meaning it writes whatever it sees in setup game controllers .Of course i am talking about the ID order. 
My problem though is that i have logitech g13 which  i use and is stuck at the top whatever i do .
With nomal laucncher what i did to overcome this is to write protect the file be ticking the option Read only in properties.  So i edit it manually once  and put at the end  after the Cougar the G13  so my joystick DX button start at 1,2 and throtlle 33,34 and so on.. 
Now G13 is id 1 ( i plug it in and out in various ports of my pc but is stupborn !)
Is there a way to help . Or i have to unplug it tottaly or chenge in the program the DX buttons mapping (ie adding 32) 
It tould be nice to not let the program write the file in case i dont want to..

Any suggestion?

**Comment by vakosel** [comment]
In coclusion is very easy to mess up the order in game contorllers ID. So is there any possiblity for the user to choose the right order once and leave it  there ?  That is the question

**Comment by chihirobelmo** [comment]
You can enable 'launch without override' checkbox and Alt launcher will not overwrite any setup files in BMS, but it also means alt launcher will not work as a key/axis configurator and you have to assign keys via BMS UI.
