### ISSUE TITLE
Other Launchers

### ISSUE THREAD

**Issue by Todd1215** [chihirobelmo/FalconBMS-Alternative-Launcher#15]
Great utility first off. This is more of an enhancement than an issue.

Would it be possible to add additional launchers such as Yame64, RTTClient / RTTServer. I like having the single interface for everything.

**Comment by Hawkeye4040** [comment]
I know RTT Client/Server are on the list if you provide a list of all the desired programs I'm sure we can add them if they make sense I'll bring it up.

**Comment by chihirobelmo** [comment]
New RTTClients shortcuts have been added. YAME64 has not been updated recently so no support.
