### ISSUE TITLE
DeviceSorting.txt keeps changing

### ISSUE THREAD

**Issue by bdlchicago** [chihirobelmo/FalconBMS-Alternative-Launcher#19]
Every time I launch hub.exe my devicesorting.txt gets changed and my controllers are out of order. Are you still supporting this with 4.34? Also, I couldn't even find BenchmarkSims in my registry to backup.

**Comment by jjhritz** [comment]
Alt Launcher seems to automatically sort devices in ascending order by GUID whenever it starts.  It also ignores any read-only flags set on the file by the OS, so it doesn't look like there's any way to prevent this from happening.

**Comment by chihirobelmo** [comment]
commenting on old posts to clean up the issues.
If you don't want AL to change Devicesorting, you are knocking the bottom out of the concept of AL. sorry.
