### ISSUE TITLE
POV Device ID not assigned/assigned wrong

### ISSUE THREAD

**Issue by Martijnve23** [chihirobelmo/FalconBMS-Alternative-Launcher#26]
First of all: Thank you for the great launcher! You did a great job

In 1.50 and 1.51 I am having an issue with assigning POV Hats.

I have a logitech extreme 3d pro and a TWCS throttle. Within the launcher, both are recognized as POV1 and I can only assign the POV of the logitech.

Is there any way of ensuring the POV of the throttle is recognized as POV2? Or is this just a known limitation within the software currently?
And if it is a limitation, is there a way to manually override only the POV of the throttle?

**Comment by arithex** [comment]
(Old issue, I know but..) 
Fixed in https://github.com/chihirobelmo/FalconBMS-Alternative-Launcher/pull/101

Latest debug-build from develop branch => https://github.com/chihirobelmo/FalconBMS-Alternative-Launcher/releases/tag/v2.4.0.2
