### ISSUE TITLE
Keymapping works only on first usb game controller

### ISSUE THREAD

**Issue by piotrraczynski** [chihirobelmo/FalconBMS-Alternative-Launcher#28]
FalconBMS Alternative launcher v1.51
FalconBMS 4.34.4

I observed that Keymapping seems to work only on first game controller listed by Windows in USB game controllers window.

I have Thrustmaster Hotas X with which both Axis and Key mappings works great with this alternative launcher, awesome.

However when I plugin second controller (in my case it's Arduino leonardo where I use two rotary encoders and a few toggle switches), then only Axis mapping works, keymapping does not work at all. 

When I unplug my Hotas, then keymappings on my Arduino starts to work perfectly (but I lost my hotas), it effectively makes my Arduino first on the list, thus my suspicion that only with the first one on the list, keymapping works at all.

important note, the keymappings works in the launcher itself for all game controllers but it seems that BMS only honors those from the first game controller listed. As I already mentioned axis mapping works great for all input devices.

**Comment by Korneg** [comment]
Hi,
I had a similar problem. I solved it by replacing the `break` in the file OverrideSetting.cs (SaveKeyMapping - line 900) by a `continue`. But please be careful, I did not check for any side-effects.

The loop is writing the key mapping file. If it finds the primary device pov, it stopps the execution immediately, ignoring all devices that are behind the primary device in the list.

**Comment by Nacman** [comment]
> Hi,
> I had a similar problem. I solved it by replacing the `break` in the file OverrideSetting.cs (SaveKeyMapping - line 900) by a `continue`. But please be careful, I did not check for any side-effects.
> 
> The loop is writing the key mapping file. If it finds the primary device pov, it stopps the execution immediately, ignoring all devices that are behind the primary device in the list.

Any chance I might get the compiled version you have? I have this issue as well and can't compile the code myself.

**Comment by chihirobelmo** [comment]
Sorry for not checking GitHub for months. I just fixed the issue in v1.52. Thank you Korneg for finding out the solution.

**Comment by Korneg** [comment]
Thank you for fixing it. I really like that launcher.
