### ISSUE TITLE
Certain keys in WinWing's Super Tarsus throttle can not be mapped despite registering

### ISSUE THREAD

**Issue by Andytr1** [chihirobelmo/FalconBMS-Alternative-Launcher#29]
I installed WinWing's Super Tarsus throttle. The alternative launcher is not allowing me to map certain direct X buttons - even though they are still displayed at the bottom, to the right of the `assignment` label. 
However, when I open a dialog to map, and press the key, nothing happens.
Some examples:
The speed brake switch on Win Wing is comprised of three DX switches:
DX20, momentary, used to extend
DX19, momentary, off position, default
DX18, hold, used to retract 

Of these three buttons, only DX19 is mappable. The other 2 (DX20 and DX18) can't be assigned to a key, despite being picked up in the main GUI.
This happens with a few other buttons as well. The buttons are mappable in other software/sims and are visible in Windows manage USB devices.
Any help is appreciated !

**Comment by Andytr1** [comment]
Doing investigation now. Looks like there is a bug in `KeyMappingWindow.xaml.cs::JoystickButtonMonitor::133`. For some reason the buttons[19] is equal to neutralButtons[5].buttons[19] even though it is being pressed. The value in the neutralButtons[5].buttons[19] is 128.  5 is device id for WinWing throttle.

**Comment by Andytr1** [comment]
The primary cause appears to be timing/multiple `getNeutralPosition` calls. By having only a single `getNeutralPosition` call on WindowLoaded appears to resolved my specific issue. I am curious, what is the benefit of having multiple calls to `getNeutralPosition`  inside `JoystickButtonMonitor` ?

**Comment by NoelShourai** [comment]
Somewhat related, but I'm also having the same issue on a similar device, the WinWing Orion F-16EX. I was not able to map the paddle switch correctly; when the paddle is depressed it inputs DX8, and when it is released it inputs DX7. However, the Alternative Launcher does not seem to be able to read the DX8 input and only reads the DX7 input.

**Comment by mrcultureshock** [comment]
> The primary cause appears to be timing/multiple `getNeutralPosition` calls. By having only a single `getNeutralPosition` call on WindowLoaded appears to resolved my specific issue. I am curious, what is the benefit of having multiple calls to `getNeutralPosition` inside `JoystickButtonMonitor` ?

I'm have the Winwing control panels and I have problems binding 2-way/3-way toggles because the AL doesn't always see the keys. Where can I find the calls above such as getNeutralPosition?

**Comment by chihirobelmo** [comment]
ON-ON switch should be fixed now.

**Comment by mrcultureshock** [comment]
How do I use the On-One switch feature? The toggles on Winwing panels still
don't get triggered consisistently, just like the previous version of the
AL.

Thanks!

Nicolas
