### ISSUE TITLE
Alternative Launcher no longer starts up

### ISSUE THREAD

**Issue by NoelShourai** [chihirobelmo/FalconBMS-Alternative-Launcher#33]
On a fresh install of Windows 10 on a brand new PC, the Alternative Launcher no longer starts up. No error message is given, the program just silently starts up and then quits. (Also of note that if it cannot detect the BMS install, it does display a message indicating so, so the program is indeed running for at least a short moment) Windows Event Viewer displays the following:

```
Fault bucket 2020227229049621608, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Hub.exe
P2: 1.6.0.0
P3: 5fe0339c
P4: KERNELBASE.dll
P5: 10.0.19041.662
P6: e6477cce
P7: c000041d
P8: 0012a892
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFCB7.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFD73.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFD84.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFD84.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDA4.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Hub.exe_3c73a945bd2b342539b878f720a7f0c792d72796_bac662d5_e27348e9-4a11-433a-b130-63989117a987

Analysis symbol: 
Rechecking for solution: 0
Report Id: 92372354-fe86-4afc-b7b9-521b3eb3ea0a
Report Status: 268435456
Hashed bucket: 3c3f941b399723038c0949f611130c68
Cab Guid: 0
```
Edit: Found a thread with a similar issue to this with a dlls.zip, extracted those and the program seems to run now. However the latest release already comes with the exact same files, why don't those work?

**Comment by Hawkeye4040** [comment]
I will look into this it'll take me a little time to do so.

**Comment by Hawkeye4040** [comment]
That is a good question. I will try to reproduce the erroneous behavior, I have yet to be able to do so. If you do find something more specific it'd help me do so too so I'd love to see that. 

For now I'll keep analyzing and trying to hunt down that issue. The first code cleanup passes are helping with that. I'll work on using ReSharper to help continue to clean it up I'll also try to organize everything a bit more following your schema. What'd take weeks to do by hand ReSharper can do in minutes for us.

**Comment by Hawkeye4040** [comment]
@NoelShourai has this issue been resolved for you yet? We are working on cleaning up a lot right now.

**Comment by NoelShourai** [comment]
I haven't updated my copy of the launcher since I posted about this, so I think it's safe to assume that without using the files from dlls.zip the issue is not normally resolved without that particular workaround.

**Comment by Hawkeye4040** [comment]
Okay we can re-open this one if it happens again. With so many changes it would certainly call for fresh logs to resolve any issues.
