### ISSUE TITLE
How to proceed with the BMS update?

### ISSUE THREAD

**Issue by Sierra64** [chihirobelmo/FalconBMS-Alternative-Launcher#40]
The update is probably next to 4.35 U2 and I would like to know how to do with alternative launcher. Do I have to uninstall it before updating to U2? Can the update be done without acting on the alternative launcher?

I would like to know the exact steps to follow to avoid conflicts between the programs.

Thank you very much for this excellent tool.

**Comment by oakdesign** [comment]
Most likely you will just apply he U2 update. BMS intermediate updates usually don't change anything in User/Config folder and don't include a Hub.exe.

**Comment by Sierra64** [comment]
Thank you very much for your reply!
