### ISSUE TITLE
Support SimHotasShift callback (vs SimHotasPinkyShift)

### ISSUE THREAD

**Issue by arithex** [chihirobelmo/FalconBMS-Alternative-Launcher#44]
In 4.35, BMS added `SimHotasShift` callback as a way to do dx-shifting, without invoking the `SimPinkySwitch` callback on short-press.

I can't seem to get AL to use this though .. it seems to always want to use `SimHotasPinkyShift` (and I see that appears hardcoded, in several places).

Background: I've built a separate tool to invoke a key-press, upon short-press of a dx button (similar to Joy2Key or AutoHotkey et al) but apparently it's of little use to folks who rely on Alt Launcher to modify hotas bindings .. which is most folks. :)

**Comment by chihirobelmo** [comment]
committed to the develop branch. will be supported in 2.1.0
