### ISSUE TITLE
stuck SimHotasPinkyShift

### ISSUE THREAD

**Issue by mmikulic212** [chihirobelmo/FalconBMS-Alternative-Launcher#46]
v2.0 has stuck SimHotasPinkyShift bug again...

**Comment by Hawkeye4040** [comment]
@chihirobelmo message me later about how to set up a unit test for this. This way you won't have to manually test for the reoccurrence of this bug while still ensuring it does get tested by something (in this case a machine). I don't know why it's the most overlooked topic in computer science but it's going to solve this issue right here.

**Comment by chihirobelmo** [comment]
@mmikulic212 Hi, what's "stuck SimHotasPinkyShift bug" is like?

**Comment by mmikulic212** [comment]
I am trying to reproduce, but with no luck. Sorry for really vague report.

When you press PinkySwitch DX Shift button it will stay in shifted state until I press it again (like capslock). Normal callbacks don't work, but shifted are working without pressing shift button. 

HOTAS: TM warthog stick and TM TWCS. HOTAS is ok. I don't use TM software.

Pinky Switch (DX SHIFT) is assigned to DX3;DX3 SHIFT

When I restore backup files it worked ok again.

below is part of BMS Auto key file:

```

#======== vJoy Device ========

#======== Joystick - HOTAS Warthog ========
SimTriggerFirstDetent 32 -1 -2 0 0x0 0
SimPickle 33 -1 -2 0 0x0 0
SimEmergencyJettison 161 -1 -2 0 0x0 0
SimHotasPinkyShift 34 -1 -2 0 0x0 0
SimHotasPinkyShift 162 -1 -2 0 0x0 0
SimAPOverride 35 -1 -2 0 0x0 0
SimMissileStep 36 -1 -2 0 0x0 0
SimTriggerSecondDetent 37 -1 -2 0 0x0 0
SimTMSUp 38 -1 -2 0 0x0 0
SimTMSRight 39 -1 -2 0 0x0 0
SimTMSDown 40 -1 -2 0 0x0 0
SimTMSLeft 41 -1 -2 0 0x0 0
SimDMSUp 42 -1 -2 0 0x0 0
SimICPNext 170 -1 -2 0 0x0 0
SimDMSRight 43 -1 -2 0 0x0 0
SimDMSDown 44 -1 -2 0 0x0 0
SimICPPrevious 172 -1 -2 0 0x0 0
SimDMSLeft 45 -1 -2 0 0x0 0
SimCMSUp 46 -1 -2 0 0x0 0
SimCMSRight 47 -1 -2 0 0x0 0
SimCMSDown 48 -1 -2 0 0x0 0
SimCMSLeft 49 -1 -2 0 0x0 0
SimSlapSwitch 50 -1 -2 0 0x0 0

#======== Joystick - HOTAS Warthog : POV ========
AFElevatorTrimUp 0 -1 -3 0 0x0 0
SimDoNothing 2 -1 -3 0 0x0 0
SimDoNothing 0 -1 -3 1 0x0 0
SimDoNothing 2 -1 -3 1 0x0 0
AFAileronTrimRight 0 -1 -3 2 0x0 0
SimDoNothing 2 -1 -3 2 0x0 0
SimDoNothing 0 -1 -3 3 0x0 0
SimDoNothing 2 -1 -3 3 0x0 0
AFElevatorTrimDown 0 -1 -3 4 0x0 0
SimDoNothing 2 -1 -3 4 0x0 0
SimDoNothing 0 -1 -3 5 0x0 0
SimDoNothing 2 -1 -3 5 0x0 0
AFAileronTrimLeft 0 -1 -3 6 0x0 0
SimDoNothing 2 -1 -3 6 0x0 0
SimDoNothing 0 -1 -3 7 0x0 0
SimDoNothing 2 -1 -3 7 0x0 0

#======== vJoy Device ========

#======== TWCS Throttle ========
SimToggleMissileCage 96 -1 -2 0 0x0 0
SimCATSwitch 224 -1 -2 0 0x0 0
SimWheelBrakes 98 -1 -2 0 0x0 0
AFGearToggle 226 -1 -2 0 0x0 0
SimRadarElevationUp 99 -1 -2 0 0x0 0
SimRadarElevationDown 100 -1 -2 0 0x0 0
SimCursorEnable 101 -1 -2 0 0x0 0
SimRadarCursorZero 229 -1 -2 0 0x0 0
SimRangeKnobUp 102 -1 -2 0 0x0 0
ToggleNVGMode 230 -1 -2 0 0x0 0
AFBrakesIn 103 -1 -2 0 0x0 0
SimSpotLight 231 -1 -2 0 0x0 0
SimRangeKnobDown 104 -1 -2 0 0x0 0
SimVisorToggle 232 -1 -2 0 0x0 0
AFBrakesOut 105 -1 -2 0 0x0 0
ToggleSmoke 233 -1 -2 0 0x0 0
SimICPAG 106 -1 -2 0 0x0 0
SimSelectSRMOverride 107 -1 -2 0 0x0 0
SimDeselectOverride 108 -1 -2 0 0x0 0
SimSelectMRMOverride 109 -1 -2 0 0x0 0
SimJfsStartDown 237 -1 -2 0 0x0 0

#======== TWCS Throttle : POV ========
SimTransmitCom1 1 -1 -3 0 0x0 0
SimAud1Com1 3 -1 -3 0 0x0 0
SimDoNothing 1 -1 -3 1 0x0 0
SimDoNothing 3 -1 -3 1 0x0 0
SimCommsSwitchRight 1 -1 -3 2 0x0 0
SimExtlPower 3 -1 -3 2 0x0 0
SimDoNothing 1 -1 -3 3 0x0 0
SimDoNothing 3 -1 -3 3 0x0 0
SimTransmitCom2 1 -1 -3 4 0x0 0
SimAud1Com2 3 -1 -3 4 0x0 0
SimDoNothing 1 -1 -3 5 0x0 0
SimDoNothing 3 -1 -3 5 0x0 0
SimCommsSwitchLeft 1 -1 -3 6 0x0 0
SimAVTRToggle 3 -1 -3 6 0x0 0
SimDoNothing 1 -1 -3 7 0x0 0
SimDoNothing 3 -1 -3 7 0x0 0
```

Update: Now I see there are  vJoy devices involved here.

**Comment by Hawkeye4040** [comment]
@chihirobelmo I think this is the bug I was telling you about on Discord before. It sounds very similar where this exact part is being overwritten by something inappropriately. I would wager there is a method call buried in a loop somewhere that shouldn't be there causing this.

 I'd start looking in whatever method you have to create the file streams at run-time first. I'll be trying to dig through and find these lines myself. Any file names, in particular, these should be found in? If I need to elaborate more give me a call.

**Comment by Hawkeye4040** [comment]
If we can't find it the diagnostics logging would be able to help pinpoint this, which is one of the many reasons why I emphasized it.

**Comment by chrismcgourty** [comment]
Hi,

not sure I'm adding here as I'm new to BMS and wanted to give feedback on what I saw.
Clean install of 4.35.

Backed up and deleted X:\Falcon BMS 4.35\User\Config\BMS - Full.key

Copied X:\Falcon BMS 4.35\Docs\01 Input Devices\03 HOTAS Setup\Saitek X-55\BMS - BasicDX X-55.key 

As BMS - Full.key 

To X:\Falcon BMS 4.35\User\Config\BMS - Full.key

Launched F4, set up axis controls and HOTAS shifted DX works as intended. Saved config as BMS - Full.key. Exited software.

Install FalconBMS-Alternative-Launcher

Launched F4, no shifted (DX) bindings work.

Thank you.

**Comment by arithex** [comment]
If this was an AL code-bug, it must have been fixed some time ago .. haven't seen it repro.
