### ISSUE TITLE
Add -mono option to command line to get a logfile

### ISSUE THREAD

**Issue by JBoysen1** [chihirobelmo/FalconBMS-Alternative-Launcher#47]
In order to get a logfile to help with debugging crashes and problems, the command line should contain "-mono". See for instance 

https://forum.falcon-bms.com/topic/21636/fmap-weather-system-with-auto-update-is-broken/12#

**Comment by chihirobelmo** [comment]
Hi, You can enable the "DEBUG" button to put -mono line and launch BMS with a debug window.

**Comment by Hawkeye4040** [comment]
Perhaps adding a button somewhere like in the settings menu. I can walk you through the binding on Discord if you need it. If you give me a few days I might have time to help implement it too. That was one of my ideas when we first started it. I love the command line option. That's probably the best way to bind everything as well. Using the command line objects as a base so both CL arguments and button events alike are wired up to the same event and callbacks all nice and neat.

[Command Binding Class](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.commandbinding?view=windowsdesktop-6.0)
