### ISSUE TITLE
BMS Alternative launcher Issue 

### ISSUE THREAD

**Issue by ArcherFO** [chihirobelmo/FalconBMS-Alternative-Launcher#48]
A friend of mine sent me the version 2.0 and upon running it I am getting this errors

https://cdn.discordapp.com/attachments/901819506018627584/922241370469597214/20211219_163745.jpg

https://cdn.discordapp.com/attachments/901819506018627584/922241469807464469/20211219_163803.jpg

https://cdn.discordapp.com/attachments/901819506018627584/922241535674810398/20211219_163827.jpg

**Comment by Hawkeye4040** [comment]
What!? You're still dumping the log into a message box instead of a log file? I thought we changed that back @chihirobelmo.

**Comment by Hawkeye4040** [comment]
I just want to throw it out there the feature I implemented to help out here was take and then just shit all over. Please don't blame me for it. I tried my best to help. I spent hours and hours on the logging feature only to have it well this.... Like I said this one isn't on me and I'm not going to help if every time I fix something you turn around and immediately break it when you didn't even have to touch it at all.

**Comment by Hawkeye4040** [comment]
This is the equivalent of me giving you an xmas present you saying wow thanks and then not only smashing it right in front of me but also spitting on it. That's how I feel after seeing this after all the work I put in on this feature to help and you just dump it into a message box. 

Let the record show that I tried to help you fix this but then you turned around and even fucked that up. Done.

**Comment by chihirobelmo** [comment]
@ArcherFO 

can you give me your .xml files in User/Config of BMS install dir?

@Hawkeye4040 

The first time you gave me the Diagnostics logic you made, it could not save log text into AppData.

https://github.com/chihirobelmo/FalconBMS-Alternative-Launcher/commit/723c818c799b115c7c2c5b53b9e56a86eb938402

I had to temporarily fix it to show an error message into the message window until I found a way to fix it. 

https://github.com/chihirobelmo/FalconBMS-Alternative-Launcher/commit/8395800fac88a20a5cf17ce11d9f92887a8106c4

That's in the v2.0 release. 
Later, I found a way to save logfile into AppData and I fixed, pushed commit to the master.

https://github.com/chihirobelmo/FalconBMS-Alternative-Launcher/commit/92963d546bc448bfbfed4115e6e29260c94dd8c8

It's not released as a package yet, but I've never broken it.

**Comment by Hawkeye4040** [comment]
Oh thank you! So this isn't that one yet? 😂 I was so pissed to see that come up again!

**Comment by ArcherFO** [comment]
@chihirobelmo Sure I will send my .xml file. On the side bar just reading the first 4 replies I was wow what did I do? This is the very first time I have ever contacted you lol

**Comment by ArcherFO** [comment]
@chihirobelmo https://drive.google.com/file/d/1PAMuYdwRMOW9RuTPzx7g7JDujebBuTlM/view?usp=sharing

**Comment by Hawkeye4040** [comment]
> @chihirobelmo Sure I will send my .xml file. On the side bar just reading the first 4 replies I was wow what did I do? This is the very first time I have ever contacted you lol

Sorry that was my fault. There is this insanely annoying bug that keeps resurfacing on us! One I fixed and someone else came back and was like what's this crap? And then proceeded to re-break it. I'll admit it was a band-aid patch for now but it was working.

**Comment by ArcherFO** [comment]
> > @chihirobelmo Sure I will send my .xml file. On the side bar just reading the first 4 replies I was wow what did I do? This is the very first time I have ever contacted you lol
> 
> Sorry that was my fault. There is this insanely annoying bug that keeps resurfacing on us! One I fixed and someone else came back and was like what's this crap? And then proceeded to re-break it. I'll admit it was a band-aid patch for now but it was working.

So Can I get the fix for my issue?

**Comment by chihirobelmo** [comment]
@ArcherFO 
Hi, sorry kept you waiting.
I found your XML files corrupted but not sure how and when it happened.
Can you tell me
1. will it corrupt again if you remove XML then redo setup?
2. what is your Windows language?

**Comment by Lloir** [comment]
Hi there, I have the exact same issue with the exact same error messages

I've re-run the installer and done a repair -- same error
Uninstalled - reinstalled -- same error
Deleted Stock folder -- Falcon regenerated -- same error

Windows Language is British English so the UTF-8 in the the XML files is fine for me. This is based on the pre-release

**Comment by ArcherFO** [comment]
> Hi there, I have the exact same issue with the exact same error messages
> 
> I've re-run the installer and done a repair -- same error Uninstalled - reinstalled -- same error Deleted Stock folder -- Falcon regenerated -- same error
> 
> Windows Language is British English so the UTF-8 in the the XML files is fine for me. This is based on the pre-release

I just deleted the XML files and it worked just fine. I think your anti virus is causing the issue.

**Comment by chihirobelmo** [comment]
Hmmm. then maybe it's not a matter of Windows Language.
do you remember anything you did before XML broke?

**Comment by ArcherFO** [comment]
> Hmmm. then maybe it's not a matter of Windows Language. do you remember anything you did before XML broke?

I switched from having a Saitek X-65 to Warhog stick and the Launcher would not load.
