### ISSUE TITLE
Bag on EMF Theater with airfields (wrong positions) on main map

### ISSUE THREAD

**Issue by Giannis-Plt** [chihirobelmo/FalconBMS-Alternative-Launcher#49]
I installed version 2 Alternative Launcher,
I have a bug with EMF theatre.
When i start the game from the new launcher the airports on the map are in wrong position.

https://imgur.com/bNzi9Vt

I noticed on theater.lst file that launcher adds by it self some lines,
this lines :
Add-On emf\F4patch\Big Map\emf.tdf
Add-On emf\F4patch\Reddog Map\emf.tdf
Add-On emf\F4patch\Small Map\emf.tdf
Add-On emf\Theaterdefinition\emf.tdf

when i start the launcher , before pressing run game , i delete the 3 firsts lines, and then run the game,
the map is ok and the airports.
Does anyone knows why is this happening? how i can prevent this auto adding lines?

**Comment by chihirobelmo** [comment]
oh, I didn't know EMF had alternate tdf files in F4pathch folder.
I will exclude the folder from auto theater detect function.

**Comment by chihirobelmo** [comment]
Solved in develop branch. Fix will be included to 2.1.0
