### ISSUE TITLE
Suggestion: for a settings key on  alternative launcher

### ISSUE THREAD

**Issue by Giannis-Plt** [chihirobelmo/FalconBMS-Alternative-Launcher#51]
It would be much better if we could edit :
User/Config/axismapping.dat
User/Config/DeviceSorting.txt
User/Config/Falcon bms.cfg
User/Config/joystick.cal
from alternative launcer. 
When i try to change something from config directory,  Alt. Launcher  auto changes them. 
 I suggest an edit key from the program ....
Thank you.
PS : the program is fantastic !  very nice job

**Comment by chihirobelmo** [comment]
AL auto generates 3of those
I don't want to add manual edit for them as I want AL to be for BMS beginner:

- User/Config/axismapping.dat
- User/Config/DeviceSorting.txt
- User/Config/joystick.cal

I was also thinking bms.cfg editor.
Maybe it would be a different app but can be integrated into AL.

thx.

**Comment by Giannis-Plt** [comment]
Thank you. 
Ok i understand the help for beginners, keep in mind the advanced users.
You would be a lot of help...
