### ISSUE TITLE
Invert Throttle Axis

### ISSUE THREAD

**Issue by kkernan** [chihirobelmo/FalconBMS-Alternative-Launcher#53]
It would be nice to be able to invert the throttle axis as mine is reversed.

**Comment by chihirobelmo** [comment]
IIRC BMS does not support throttle invert thus AL, but I'll check for 4.36

**Comment by kkernan** [comment]
I believe 4.36 does and I thought 4.35 too, but I could be mistaken. In 4.36 it's definitely in the advanced section.

**Comment by chihirobelmo** [comment]
Oh yeah! Confirmed 4.36 has a throttle axis invert available. I'll add it to the ToDo list. thx.

**Comment by chazflyz** [comment]
Yeah would be great to get an invert axis throttle option with 4.36.   Currently, when I launch AL, the invert axis option (in-game) ADVANCED tab is always reset off.  I have to check it on before I fly.  Only way to stays on is if I don't use AL and just launch vanilla.    But I'd rather use AL!  Anyways, thanks for AL and all you do to keep it updated.

**Comment by holyorangejuice** [comment]
I'm glad this was already reported. I'm new to BMS and couldn't understand why it wasn't in there.

**Comment by chihirobelmo** [comment]
committed to develop branch, will be supported in 2.1.0

**Comment by kkernan** [comment]
This doesn't appear to assign the idle/afterburner detent correctly. Once they are set it seems everything above idle is considered afterburner. If it would be helpful I could provide a proper configuration set in game and one intended to be set the same way in the alternative launcher. Alternatively it might be nice if you could configure alternative launcher to not always overwrite the axis files, that way you could use it for just button assignments. Anyhow, thanks for all the work you do. I'm sure these upgrades are a pain.
