### ISSUE TITLE
dx signals that alt launcher will list at the bottom in the key bind page will not be seen in the bind menu

### ISSUE THREAD

**Issue by chihirobelmo** [chihirobelmo/FalconBMS-Alternative-Launcher#55]
From BMS forum

https://forum.falcon-bms.com/topic/10789/falcon-bms-alternative-launcher-easy-setup-keep-joystick-assignments/775?_=1651108565106

> [Cloudless](https://forum.falcon-bms.com/user/cloudless) [about 11 hours ago](https://forum.falcon-bms.com/post/342214)
> Not sure this is the right place for this, but I’m having an issue with binding. Sometimes dx signals that alt launcher will list at the bottom in the key bind page will not be seen in the bind menu. In this case it is my ww f16 stick, the paddle switch switches from 7 to 8 when pressed in. 8 shows attention bottom of alt launcher, but 8 will not bind. Is there a way to bind using bms and have alt launcher not override it again? Or some other workaround? I might just set it to 7 release to get the same effect. Slt launcher has this issue with toggle switches too sometimes, although with persistence they will work.

**Comment by javelin10** [comment]
I have the same joystick as Cloudless; the WinWing F-16EX. The paddle switch is both an analogue axis and a two button 'rocker' type switch. It constantly sends the DX7 assignment until you pull the paddle all the way in whereupon DX7 releases and DX8 fires.  We would like to bind "simAPOverride" to DX8 but even though AL recognises both DX events on the KEYMAPPING tab, it wont bind DX8 on the binding dialog. Binding DX7 on release is no problem but it doesn't work as expected in game. The DX7 must be interfering somehow.

**Comment by chihirobelmo** [comment]
confirmed no problem with WinWing F-16EX with the latest version

**Comment by javelin10** [comment]
Yep seems to bind as desired no problems yet. Thanks!!
