### ISSUE TITLE
512DX Limit in 2.10

### ISSUE THREAD

**Issue by Mustang-25** [chihirobelmo/FalconBMS-Alternative-Launcher#57]
I know nothing about how all this coding works but I had [this conversation on the BMS discord](https://discord.com/channels/263470085560205313/631475612715843615/968228256828514395) last week where it was found that the DX limit is 4096. I'm already very thankful for the 128 input support and being able to increase the total number of devices would be fantastic!

**Comment by chihirobelmo** [comment]
thx! I fixed the v2.1.0 description.
