### ISSUE TITLE
Rotary switch assignment difficulty

### ISSUE THREAD

**Issue by nxtsem** [chihirobelmo/FalconBMS-Alternative-Launcher#60]
The keymapper has some difficulty detecting the DX switches associated with a rotary type switch.  For example, a type of switch where one of several switch positions are always activated.  It can take a few tries to get all of these switches assigned properly.  

There were no problems with detecting and assigning the momentary type buttons.  Thanks for the excellent launcher.

**Comment by chihirobelmo** [comment]
Hi, on-on-on switches may have a problem in AL. I'll try to fix it.

**Comment by chihirobelmo** [comment]
should be fixed now...

**Comment by nxtsem** [comment]
Yes, it works well.  Thank you.  - Phil  

    On Friday, January 6, 2023 at 06:47:03 AM MST, chihirobelmo ***@***.***> wrote:  
 
 


should be fixed now...
