### ISSUE TITLE
Deleting 4.35 folder causes launcher to crash

### ISSUE THREAD

**Issue by ajalberd** [chihirobelmo/FalconBMS-Alternative-Launcher#76]
Title. Deleting BMS 4.35 folder causes the launcher to crash with the following log:

I can no longer use the launcher, at startup it gives this error. Uninstalling and reinstalling does nothing, either.

[Launcher_Log.txt](https://github.com/chihirobelmo/FalconBMS-Alternative-Launcher/files/9491933/Launcher_Log.txt)

**Comment by chihirobelmo** [comment]
fixed in the next version...will be included in BMS4.37
