### ISSUE TITLE
keyfile overide or importing other existing keyfile

### ISSUE THREAD

**Issue by mmikulic212** [chihirobelmo/FalconBMS-Alternative-Launcher#77]
[feature request?]
hi, there was an keyfile overide checkbox in earlier versions of alternate launcher which I am missing. if this feature is nit supported anymore is it possible to implemet some sirt of import function from existing keyfile? its pain to do it manualy when i already have it. 
i tried to overwrite BMS - Auto.key, but luncher is smart enaugh to overwrite it again with previous settings or defaults

thanks,
Mike

**Comment by AJamesLiptak** [comment]
Hear hear. I second this request.
