### ISSUE TITLE
Snowplow bind does not work properly in game?

### ISSUE THREAD

**Issue by zekecounter** [chihirobelmo/FalconBMS-Alternative-Launcher#78]
under keymapping tab, SHORT; Radar snowplow bind

anyone else have this issue? im force to press osb buttons on tgp/fcr to get SP mode to work. pressing my assigned hotas key  doesn 

![image](https://user-images.githubusercontent.com/78181804/204177484-f01a7c70-8dbf-456f-a372-7c07868b26d0.png)

**Comment by arithex** [comment]
This is a BMS bug (or deprecated feature?), not an AL issue.
https://forum.falcon-bms.com/topic/25468/snowplow-hotas-issue
